### ISSUE TITLE
dlg.rs missing resources

### ISSUE THREAD

**Issue by milliorn** [urothis/rs_nwn_nasher_types#8]
This is missing from the test.dlg.json, yet found in src/dlg.rs

`dlg.rs`

```rs
/// Field indicating whether zooming in is prevented during the conversation
#[serde(skip_serializing_if = "Option::is_none", rename = "PreventZoomIn")]
pub prevent_zoom_in: Option<NwValue<u8>>,

/// Field representing the quest entry of the entry
#[serde(skip_serializing_if = "Option::is_none", rename = "QuestEntry")]
pub quest_entry: Option<NwValue<u32>>,
```

**Comment by urothis** [comment]
![image](https://github.com/urothis/rs_nwn_nasher_types/assets/287208/8317f4b0-3de9-4626-9714-638bcb0cd2b9)
![image](https://github.com/urothis/rs_nwn_nasher_types/assets/287208/ce98f6e6-402c-4d85-abe5-d32f5ed2302e)

Validated fields
